name: 'NODE INSTALL BUILD'
description: 'Node Install and Build'
inputs:
  node_version:  # version
    description: 'Version'
    required: true
    default: 'production'
  add_tsc:  # runs aditional tsc command
    description: 'Runs aditional tsc command'
    required: true
    default: 'false'
  change_permissions:
    description: 'Change permissions'
    required: true
    default: 'false'
  link:
    description: 'Link back'
    required: true
    default: 'false'
  build_options:
    description: 'Build Options'
    required: true
    default: ''
  install_options:
    description: 'Install Options'
    required: true
    default: ''
  folder:
    description: 'Folder'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
  - name: Use Node.js ${{ inputs.node_version }}
    uses: actions/setup-node@main
    with:
      node-version: ${{ inputs.node_version }}
      registry-url: https://registry.npmjs.org
  - name: Change Dir
    if: ${{ inputs.folder != '' }}
    run: cd ${{ inputs.folder }}
    shell: bash
  - name: Install
    uses: borales/actions-yarn@master
    with:
      cmd: install ${{ inputs.install_options }}
  - name: Make back executable
    if: ${{ inputs.change_permissions == 'true' }}
    run: chmod +rwx ./node_modules/.bin/back
    shell: bash
  - name: Set User 0
    if: ${{ inputs.change_permissions == 'true' }}
    run: npm config set user 0
    shell: bash
  - name: Set unsafe-perm true
    if: ${{ inputs.change_permissions == 'true' }}
    run: npm config set unsafe-perm true
    shell: bash
  - name: Link back 
    if: ${{ inputs.change_permissions == 'true' && inputs.link == 'true' }}
    run: ln ./node_modules/.bin/back /usr/local/bin/back
    shell: bash
  - name: show back 
    if: ${{ inputs.change_permissions == 'true' && inputs.link == 'true' }}
    run: which back
    shell: bash
  - name: Build
    uses: borales/actions-yarn@master
    env:
      ALLOWED_HOSTS: "*"
    with:
      cmd: build ${{ inputs.build_options }} # will run `yarn build` command
  - name: Build ADD
    if: ${{ inputs.add_tsc == 'true' }}
    uses: borales/actions-yarn@master
    env:
      ALLOWED_HOSTS: "*"
    with:
      cmd: tsc # will run `yarn tsc` command
